name: pre-commit-workflow

on:
  # The jobs in this GitHub action will run for pull requests on all branches
  pull_request:
    branches:
      - "*"

jobs:
  pre-commit:
    # This JOB runs the pre-commit actions from the .pre-commit-config.yaml file in the repo files.
    runs-on: ubuntu-latest
    steps:
    # 1. This step uses actions/checkout@v3 to clone the code in the GitHub actions machine.
    - name: Checkout repository code
      uses: actions/checkout@v3
  
    # 2. This step uses actions/setup-python@v3 to install python in the GitHub actions machine.
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    # 3. This step sets up and runs the pre-commit based on the .pre-commit-config.yaml file.
    - name: pre-commit check
      uses: pre-commit/action@v3.0.0
